server {
    listen 80;

    location /owner/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /owner/index.html;
    }

    location /owner {
        return 301 /owner/;
    }
}
